# -*- coding: utf-8 -*-
"""kadai_008.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrgbEtYeRTPOXXzhq2Q8cqAMG4LXfnSf
"""

from sklearn.datasets import load_wine

dataset = load_wine()
dataset

dataset.data

dataset.feature_names

import pandas as pd
df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
df.head()

dataset.target

df['category'] = dataset.target
df.head()

df.shape

X = dataset.data
y = dataset.target

from sklearn.model_selection import train_test_split

train_test_split(X, y, test_size=0.3, random_state=5)
# 以下のようにrandom_stateを指定しない場合、実行毎に結果が異なります。
# train_test_split(X, y, test_size=0.3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

print(X.shape, X_train.shape, X_test.shape, y.shape, y_train.shape, y_test.shape)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=3)

model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

model.score(X_test, y_test)